# Generated by Django 6.1 on 2026-09-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=50, unique=True)),
                ('sender', models.CharField(max_length=255)),
                ('receiver', models.CharField(max_length=255)),
                ('origin_country', models.CharField(max_length=100)),
                ('origin_state', models.CharField(max_length=100)),
                ('origin_city', models.CharField(max_length=100)),
                ('origin_address', models.CharField(max_length=255)),
                ('destination_country', models.CharField(max_length=100)),
                ('destination_state', models.CharField(max_length=100)),
                ('destination_city', models.CharField(max_length=100)),
                ('destination_address', models.CharField(max_length=255)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_method', models.CharField(max_length=50)),
                ('payment_status', models.CharField(default='Paid', max_length=50)),
                ('status', models.CharField(default='Shipment Created', max_length=100)),
                ('current_location', models.CharField(max_length=255)),
                ('next_location', models.CharField(max_length=255)),
                ('estimated_delivery', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
