# Generated by Django 6.1 on 2026-09-10 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0002_trackingupdate'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trackingupdate',
            name='date',
        ),
        migrations.RemoveField(
            model_name='trackingupdate',
            name='description',
        ),
        migrations.RemoveField(
            model_name='trackingupdate',
            name='location',
        ),
        migrations.RemoveField(
            model_name='trackingupdate',
            name='status',
        ),
        migrations.RemoveField(
            model_name='trackingupdate',
            name='time',
        ),
    ]
