# Generated by Django 6.1 on 2026-09-10 13:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0003_remove_trackingupdate_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='trackingupdate',
            name='date',
            field=models.DateField(default=datetime.date(2026, 9, 10)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackingupdate',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='trackingupdate',
            name='location',
            field=models.CharField(default='Unknown', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackingupdate',
            name='status',
            field=models.CharField(default='Shipment Created', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trackingupdate',
            name='time',
            field=models.TimeField(default=datetime.time(0, 0)),
            preserve_default=False,
        ),
    ]
