# Generated by Django 6.1 on 2026-09-12 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0004_trackingupdate_date_trackingupdate_description_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='shipping_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
