# Generated by Django 6.1 on 2026-09-12 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0005_shipment_shipping_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shipment',
            name='payment_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
    ]
