# Generated by Django 6.1 on 2026-09-15 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0006_alter_shipment_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='payment_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
