# Generated by Django 6.1 on 2026-09-22 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shipments', '0007_shipment_payment_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='shipment',
            name='item_photo',
            field=models.ImageField(blank=True, null=True, upload_to='shipment_items/'),
        ),
    ]
